### ISSUE TITLE
add a landing page with a different domain

### ISSUE THREAD

**Issue by pixsolution** [gecche/laravel-multidomain#102]
Hello

I'm using your package for multidomain project it work well eg. domain1.com.ve, domain2.com.co..... but the project need a landing page for the general domain.com that has the typical list of countries (only that)...so I don't want to add it with the add domain command because it creates an env and asks for a database etc. which is not needed because it is a simple landing page...so how to do it?

Regards

**Comment by gecche** [comment]
Hi,

this is a question which is a bit outside the scope of the package because the application serving your "main" domain, even if it is a simple landing page, is totally different from the other application serving the clients.

So, a first approach could be to do a whole different project for the main domain.

However, If you want to include the main domain in the current application, note that you don't need a database etc... but as a Laravel application you will need an .env file, so I would do so:

- I suppose domain.com is linked to the application as the default domain, so you can use the standard .env file (you have to check in your Nginx config or whatever you use as web server, but I'm not an expert in this)
- In the .env file put a "type" entry, e.g. DOMAIN_TYPE=main
- In the route file you ise for the landing, I suppose, you link the landing to "/", put something like:

`if (env('DOMAIN_TYPE') == "main") {
 Route::get("/",<LANDING>)
} else {
Route::get("/",<STANDARD CONTROLLER>)
}
`

- If you need to put only this route to that domain, use a similar guard to don't load all the other routes
`if (env('DOMAIN_TYPE') != "main") {
   <LOAD ROUTES AND ROUTE FILES>
}
`

Maybe there are also better approaches, but I hope this helps

Cheers

Giacomo
