### ISSUE TITLE
--domain option not exist

### ISSUE THREAD

**Issue by EverybodyBusiness** [gecche/laravel-multidomain#111]
I am using two Ubuntu servers 22.04, and one of them is working fine using this package. When I run php artisan list, I can check the --domain option as shown in the image below. 

<img width="1044" alt="image" src="https://github.com/gecche/laravel-multidomain/assets/102199931/16747e73-6f3f-4fc7-9830-f414b9e29947">

Both servers are using PHP 8.2 and Laravel 9. However, when I run php artisan list on a newly installed server, there is no --domain option as shown in the image below. 

<img width="1194" alt="image" src="https://github.com/gecche/laravel-multidomain/assets/102199931/3e99817d-7d49-4e82-bc73-657bfbcfce0d">

I would appreciate it if anyone could tell me a solution.

**Comment by EverybodyBusiness** [comment]
Both servers are using gecche/laravel-multidomain 5.0

**Comment by gecche** [comment]
Hi,

I'm sorry but I can't help you based on those info, because if on one server works and on another server does not work, I guess you have missed some step in the installation process.
Maybe you missed to change the Console Kernel or to extend the main container in bootstrap/app.php? Because if the --domain option does not appear probably one of these two is missing.

Cheers

Giacomo
