### ISSUE TITLE
Domain Detection function not working in v11

### ISSUE THREAD

**Issue by bafitu** [gecche/laravel-multidomain#117]
Hi,

I think the **domain_detection_function_web** closure is never initiated because of the way they changed the flow in v11.
So if you need to detect the domain based on **HTTP_HOST** instead of **SEVER_NAME** right now its not working.

Probably the **$domainParams** needs to be passed on to the static configure function e.g something like this.

`public static function configure(string $basePath = NULL, string $environmentPath = NULL, array $domainParams = [])
`

and then initialize the Application which will then assign the domainParams.

`return (new ApplicationBuilder(new static($basePath, $environmentPath, $domainParams)))
`

Then in the **boostrap/app.php** 
`return Application::configure(basePath: dirname(__DIR__), environmentPath: NULL, domainParams: $domainParams)
`

Otherwise **$domainParams** will always be empty;

Let me know what you think.

**Comment by gecche** [comment]
Hi,

sorry for the delay but I was very busy last week.

This week I will check the issue asap. However it is possible, because in L11 they have done some tweaks and also the tests are more difficult than before. 
So, maybe some minor point has to be fixed... :( 

Thanks a lot for the support 

Giacomo

**Comment by gecche** [comment]
I just updated the package using your suggestions... thanks a lot!
