### ISSUE TITLE
Question: Multiple config

### ISSUE THREAD

**Issue by tomswinkels** [gecche/laravel-multidomain#12]
Hi,

I have for each website other config. Some websites they have another logo, some website they have a video box and some not.

All this config is to much to put it in the env file.

So i think its better that every domain has own config file (array).

Than in the blade/controller i want use `config('site.var')`.

For now i have fix it by myself:

config/site.php
```php
<?php
return include(config_path(domain_sanitized(app()->domain())) . '/site.php');
```

config/site1_com/site.php
```php
<?php

return [
    'test' => 'Hello'
];
```

controller
```php
<?php

namespace App\Http\Controllers;

class IndexController extends Controller
{
    public function index()
    {
        dump(config('site.test'));
    }
}
```

Maybe you have better idea?

**Comment by gecche** [comment]
Hi,

if you need a specific config file for each domain, you can use your solution which seems ok!

However, at the package level I don't want to manage specific configuration files for each domain because it would make things more complex for a very particular situation, and I think it is out of the scope of the package.

IMHO, if you use specific configuration options for each domain mainly for frontend (logo ecc...), this is a common situation and I suggest you to use 
[https://github.com/igaster/laravel-theme](Laravel Theme package)
in combination with my package.
In that way you choose a theme for a single domain or a group of domains and all the stuff about public assets and views is managed by the theme package.

Hope this helped

Cheers

Giacomo

**Comment by tomswinkels** [comment]
@gecche 

Hi,

Wow that is great!!

Love the combination of that packages :)

This is what i do now:

- php artisan domain:add site1.com 
- php artisan theme:create site1_com

Controller
```php
<?php

namespace App\Http\Controllers;

use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{

    public function __construct()
    {
        if(app()->domain()) {
            $theme = domain_sanitized(app()->domain());
            if(\Theme::exists($theme)) {
                \Theme::Set($theme);
            }
        }
    }
}
```

<3

**Comment by gecche** [comment]
Yep!

This is what I meant before! And it is way more elegant and powerful than your first solution which, however, works. 

I have used the Theme package (and also contributed to it a long time ago) since before I started to build mine and I'm still using it. IMHO, both, combined, give a high grade of configurability in a multi domain setting.

I close the issue!

Thanks,

Giacomo

P.S.: If you like the package please leave a star ;)
