### ISSUE TITLE
domain:update_env Changes all env files even when domain option present

### ISSUE THREAD

**Issue by AMAFsoft** [gecche/laravel-multidomain#13]
```

$data = '{"APP_URL":"site1.domain.local","APP_NAME":"Site 1 name","DB_DATABASE":"site1db"}';
Artisan::call("domain:update_env --domain='site1' --domain_values='".$data."'");
```
Hi !
Runing this code changes all `.env` files, even when the `domain` option present.

What's wrong with my code?

**Comment by gecche** [comment]
Hi,

I'm sorry because I've pointed out this only in [tests docs](https://github.com/gecche/laravel-multidomain/tree/master/tests) and not in the main README file.

The problem with your code is simply that as well as the Laravel's `--env` option, the package's `--domain` option has no effect if the command is called from within the application itself.

I mean you can't use `--domain` option in `Artisan::call`. If you try the same commands from shell they should work perfectly. Please note that it is not a fault of the package: both  `--env` and `--domain` options change the environment variables, so they also changes the superglobals arrays. Once instantiated the Laravel Container, you cannot change them from an Artisan call. 

I tried to explain this in few words... it is quite complex :). However I think it makes sense because you are trying to change the domain from within a Container launched under another one. 

Cheers

Giacomo

**Comment by AMAFsoft** [comment]
Thank you for the quick ansewer!
I do unerstand what you've explained.
I think i need to try edit the env file manually using other methods out side the package.

Nice package.

**Comment by gecche** [comment]
I'm glad I made myself clear :)

Giacomo

P.S.: If you liked the package please leave a star If you haven't done yet, thank you! ;)

**Comment by AMAFsoft** [comment]
Done! ^_^
