### ISSUE TITLE
Storage:link to Public

### ISSUE THREAD

**Issue by IamJustAKid** [gecche/laravel-multidomain#15]
Hi there,

When I upload the file goes to storage/domain/app/public. I tried to create a symlink for this directory but it says. public/storage already exists for default linking.

I used php artisan storage:link --domain=domain-address

How do I create a symlink for each domain?
or
How do I use the default storage directory for all domains?

Regards,
Bilal Younas

**Comment by gecche** [comment]
Hi,

due to the behavior of the `storage:link` command in Laravel, that command write always the same link name, so, to date, you have to do symbolic manually if you want to target a different folder for each domain. I hope in future Laravel versions they update the command allowing to choose a custom link name (I will try to do a pull request when I have time)

I close the issue as this is already discussed: please refer to #11 for further details. 

Cheers,

Giacomo

**Comment by IamJustAKid** [comment]
what if I don't want to use the domain/storage path. I want to use the laravel default public path for all domains. 

How would I go about that in domains.php?

**Comment by IamJustAKid** [comment]
The other article does not help me much

**Comment by IamJustAKid** [comment]
![image](https://user-images.githubusercontent.com/20171838/71154924-7bf2c780-225e-11ea-8d72-a75145a3910e.png)
I tried this, but no effect.

**Comment by gecche** [comment]
Hi,

I'm not sure to understand your point, but if you want to target the same folder from each domain, you must not use `storage_path` because my package override that function targeting the storage folder of each domain.
I think you might use, for example, `base_path('storage/app/public')`

I don't know if this helps

Cheers

Giacomo

**Comment by IamJustAKid** [comment]
Okay

**Comment by IamJustAKid** [comment]
Great I created a separate disk and gave its root base_path('storage/app/public'). Now everything is good. 

Thanks & Regards,
Bilal Younas
