### ISSUE TITLE
When loading 2 different domains at the same time, it fails to load under a single domain

### ISSUE THREAD

**Issue by HP161** [gecche/laravel-multidomain#33]
Please help me.
When loading 2 different domains at the same time, it fails to load under a single domain.
Canot load page by Queue.

**Comment by gecche** [comment]
Hi,

I don't understand your question: could you give me more details and
possibly some example?

Thank you

Giacomo

Il giorno gio 27 ago 2020 alle ore 03:36 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
i have 2 domain , the first ,i loading domain A ,after i continue loading domain B in time
=> result domain B convert to domain A. Theme of domain B cannot load.
![f1](https://user-images.githubusercontent.com/4498007/91413378-38cd0780-e875-11ea-9f30-866184e7c560.png)
![f2](https://user-images.githubusercontent.com/4498007/91413383-3a96cb00-e875-11ea-9f7b-534438cafca7.png)

**Comment by gecche** [comment]
but from what I see, the url displayed in the browser is the same. I think that this is probably due to your webserver configuration which redirects requests of domain B to A and not due to the Laravel application nor my package.

Please check your webserver configuration, and If you are sure that it is an applicaton problem, I could try to help only if you show me the real code about domain configuration and so on. 

cheers

giacomo

Inviato da iPhone

**Comment by HP161** [comment]
Thanks for reply.
Can you tell more clearly which code file to see?

**Comment by gecche** [comment]
Hi,

first af all the virtual hosts configration of your apache/nginx.

Then the folder structure of your app in which the domains
configurations have been put.

Are you sure that you don't have a redirect from B to A? Because the
problem is that if the url in the browser is the same, the package always
loads the same configuration and hence the same theme. But my package does
not perform redirects at all, so if you write in the browser domainB.com
there is no possibility that my package redirects it to domainA.com

Cheers

Giacomo

Il giorno gio 27 ago 2020 alle ore 11:53 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
1.config vhost apache:
<VirtualHost *>
    DocumentRoot "C:/xampp/htdocs/ocop-hoa-binh/public/"
    ServerName ocopgli
![f5](https://user-images.githubusercontent.com/4498007/91509846-901ab880-e905-11ea-9335-36151cd121e2.png)
.com.vn
	ErrorLog "logs/word-error.log"
	ServerAlias *.dhphuong.com.vn
	<Directory "C:/xampp/htdocs/ocop-hoa-binh/public/">
		Options Indexes FollowSymLinks MultiViews
        	AllowOverride all
		Order allow,deny
		Allow from all
	</Directory>
</VirtualHost>
<VirtualHost *>
    DocumentRoot "C:/xampp/htdocs/ocop-hoa-binh/public/"
    ServerName ocophbh.com.vn
	ErrorLog "logs/word-error.log"
	ServerAlias *.ocophbh.com.vn
	<Directory "C:/xampp/htdocs/ocop-hoa-binh/public/">
		Options Indexes FollowSymLinks MultiViews
        	AllowOverride all
		Order allow,deny
		Allow from all
	</Directory>
</VirtualHost>
2. Themes is run good as domains. i have upload image attachs
3. config .env : 

QUEUE_CONNECTION=redis
BROADCAST_DRIVER=pusher

CACHE_DRIVER=redis
CACHE_PREFIX=sdc_cache

SESSION_DRIVER=redis
SESSION_LIFETIME=120
SESSION_SECURE_COOKIE=false

REDIS_HOST=....
REDIS_PASSWORD=
REDIS_PORT=6379
REDIS_DB=0

**Comment by gecche** [comment]
Hi,

I'm sorry but it is a bit difficult to understand and to help.

In the screenshots you sent me before, there is a domain called:

ocopgli.com.vn

but there is no reference of such domain in the virtual hosts.

Furthermore you sent me the folder structure about themes which is not
related to my package. I meant the folder structure related to my packages:
the .env files (one for each domain) and the storage folder structure.

Last thing: instead of loading Laravel have you checked the output of a
very simple index.php page in your root folder like the following under the
various domains?

<?php
echo $_SERVER['SERVER_NAME'];
?>


Cheers

Giacomo



Il giorno ven 28 ago 2020 alle ore 03:10 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
thanks you!
code bootstrap/app here:
$app = new Gecche\Multidomain\Foundation\Application(
    $_ENV['APP_BASE_PATH'] ?? dirname(__DIR__)
);

/*
|--------------------------------------------------------------------------
| Bind Important Interfaces
|--------------------------------------------------------------------------
|
| Next, we need to bind some important interfaces into the container so
| we will be able to resolve them when needed. The kernels serve the
| incoming requests to this application from both the web and CLI.
|
*/

$app->singleton(
    Illuminate\Contracts\Http\Kernel::class,
    App\Http\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Console\Kernel::class,
    App\Console\Kernel::class
);

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);
--------------------------
can you check code this?
I have 2 file env: .env.ocopgli.com.vn; .env.ocophbh.com.vn

**Comment by gecche** [comment]
Hi,

your bootstrap/app.php file seems ok.

But what is the result of the check I suggested in my previous email?
Please replace temporarily the public/index.php file with a simple php file
like this:

<?php
echo $_SERVER['SERVER_NAME']
?>

What is displayed in the browser with the urls:

ocopgli.com.vn <http://env.ocopgli.com.vn/>
and
ocophbh.com.vn <http://env.ocophbh.com.vn/>?

Cheers

Giacomo



Il giorno sab 29 ago 2020 alle ore 03:48 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
thank you!
here is result $_SERVER['SERVER_NAME'] with 2 domain
![s1](https://user-images.githubusercontent.com/4498007/91784146-6080ee80-ec2c-11ea-82d2-d80ad48fc306.png)
![s2](https://user-images.githubusercontent.com/4498007/91784150-61b21b80-ec2c-11ea-97df-47dc5a442838.png)

**Comment by gecche** [comment]
Ok,

then try this example:

- put in .env.ocopgli.com.vn this entry:
DOMAINNUMBER=1
- put in .env.ocophbh.com.vn this entry:
DOMAINNUMBER=2

replace your routes/web.php file with this simple one:

<?php

Route::get('/', function () {
    echo env('DOMAINNUMBER',3);
    return;
});

and check the result in the browser with the urls:

ocopgli.com.vn <http://env.ocopgli.com.vn/>
and
ocophbh.com.vn <http://env.ocophbh.com.vn/>

If you get 1 and 2 respectively my package should work fine and you should
find a bug in other area of your application.

Cheers

Giacomo


Il giorno mar 1 set 2020 alle ore 03:23 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
I thinks package of you not problem. I think when integrated with my project then create a bug that.
Can you support I fix this Bug?
Thanks  you!

**Comment by gecche** [comment]
Sure, no problem, but it is a bit difficult to help without having access
to the full code :)

Giacomo

Il giorno gio 3 set 2020 alle ore 03:46 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
Full code is not oke. bescause I work for hire.
Can you send project example to me?
thanks for reply!

**Comment by gecche** [comment]
Hi,

I don't want access to your full code :) I only said that it is difficult
to help without seeing it.

I don't have a project example to send: simply start from a plain Laravel
installation and add only my package to composer.json. Then try to add 2 or
more domains handled by your virtual hosts and see how it works.

Then if you have a specific question I could try to help, but
without seeing the whole app I can't do much more.

Giiacomo

Il giorno gio 3 set 2020 alle ore 11:47 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
Thanks you very much.
Here is code config/domain.php, Can you check code? additional anything ?
<?php

return [
  'env_stub' => '.env',
  'storage_dirs' => [
    'app' => [
      'public' => [
      ],
    ],
    'framework' => [
      'cache' => [
      ],
      'testing' => [
      ],
      'sessions' => [
      ],
      'views' => [
      ],
    ],
    'logs' => [
    ],
  ],
  'domains' => [
    'ocopgli.com.vn' => 'ocopgli.com.vn',
    'ocophbh.com.vn' => 'ocophbh.com.vn',
  ],
 ];

**Comment by gecche** [comment]
Hi,

your configuration seems ok.
But have you checked if there is any error in the laravel logs?

If not, first you should try to execute, under the two domains, a very
basic route displaying an environment value (for example the DB_DATABASE
entry) and see what happens. If the route displays correctly the two
disitnct database names, then modify the code by connecting to the db and
displaying a table content. Better if you do this by using a Controller
returning a view.

Giacomo



Il giorno ven 4 set 2020 alle ore 03:33 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
I have found the cause. 
<?php  echo env('DB_DATABASE') ?>
result: same database, Here is images:
![bug1](https://user-images.githubusercontent.com/4498007/92226020-436b4a80-eece-11ea-9a50-dc27171dec9d.png)
![bug 2](https://user-images.githubusercontent.com/4498007/92226026-449c7780-eece-11ea-9716-6112a546c091.png)
The system cannot get information from the .env file.
Please support

**Comment by gecche** [comment]
Hi,

but in a previous email I suggested you a simpler check than this, and you
did not tell me what were the results. The check is:

/****/
- put in .env.ocopgli.com.vn this entry:
DOMAINNUMBER=1
- put in .env.ocophbh.com.vn this entry:
DOMAINNUMBER=2

replace your routes/web.php file with this simple one:

<?php

Route::get('/', function () {
    echo env('DOMAINNUMBER',3);
    return;
});

and check the result in the browser with the urls:

ocopgli.com.vn <http://env.ocopgli.com.vn/>
and
ocophbh.com.vn <http://env.ocophbh.com.vn/>

You should get 1 and 2 respectively
/****/

What you display in the browser? Could you send me the results displaying
also the url in the browser?
Because if you see 1 and 2 the application reads perfectly the specific
.env files.


Il giorno ven 4 set 2020 alle ore 11:48 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
Hi.
Route::get('/', function () {
    echo env('DOMAINNUMBER',3);
    return;
});
result: 1.
when load 2 url at time then result: 1 or 2
I mentioned in the previous email
/*

When load 2 domain at time then:
echo env('DOMAINNUMBER',3); result: 1 or 2
*/
You give me solution to fix it?
Thanks!

**Comment by gecche** [comment]
Hi,

no, I have not a ready solution also because you are the first reporting an
issue like that.
I think that, using the last setting with the DOMAINNUMBER entry, you
should debug your application and see what happens when executing the
method

detectWebDomain

in the file

Foundation/DomainDetector.php

of my package.

If the result of that method does not correspond to the domain you have in
the url browser, I think that there is a problem in your server/virtual
machine settings.

Let me know.

Giacomo


Il giorno sab 5 set 2020 alle ore 02:42 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
I think the domain name is still correct. But when get the configuration values in .env is not correct.
It's just wrong to load 2 domains at the same time.
return Arr::get($_SERVER,'SERVER_NAME');
http://ocopgli.com.vn => ocopgli.com.vn
http://ocophbh.com.vn => ocophbh.com.vn
Can you find me the solution?

**Comment by gecche** [comment]
Ok,

so, if you are sure the SERVER_NAME is still correct, you should do a last
debug, seeing the executions of methods

'environmentFile' and 'environmentFileDomain'

in the file

'Foundation/Application.php'

of my package.

In those methods, the package loads the right environment file depending on
the domain found before.

A last question: the config has not been cached right? If so please clear
it before debug

Giacomo




Il giorno lun 7 set 2020 alle ore 03:29 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
It is oke!
Thank you very much!

**Comment by gecche** [comment]
? What happened?

Il giorno mar 8 set 2020 alle ore 10:42 Đậu Hoàng Phương <
notifications@github.com> ha scritto:

**Comment by HP161** [comment]
You are closed issue!
thank you

**Comment by gecche** [comment]
Ok,

I close the issue.

If you liked the package please leave a star and spread the word ;)

Cheers

Giacomo
