### ISSUE TITLE
Handle different APP_ENVs

### ISSUE THREAD

**Issue by danielbehrendt** [gecche/laravel-multidomain#49]
Maybe I'm missing something but how can different APP_ENVs (local, staging, production) be handled?

I think it's not a problem to all required domains to domain.php but is this the right way to have 3 entries for 1 domain?

**Comment by gecche** [comment]
Hi,

sorry for the delay but I'm currently off for some days.

I don't have my Pc right now so I'm answering for what I remember. :)

In the same Laravel way, my package should handle different ENV for a single domain just calling the files 
`.env.domain1.com.testing`
and so on.

That said, I never used such a configuration because if I need a testing environment I prefer to use a full testing domain.

Hope this helps

Cheers

Giacomo

**Comment by newlaravelcoder** [comment]
In my case, I want both the local and production DBs, files, coding to be the same. So what I did was added both domains and their envs and then used a custom helper function to strip off the extensions. For example, my two envs are:
      1. superlaravel.test (local)
      2. superlaravel.com (live)

I strip the extensions and use 'superlaravel' for all domain-specific activities so that the code works irrespective of the environment. Not sure if this is what you are trying to achieve.
