### ISSUE TITLE
how to support the laravel horizon

### ISSUE THREAD

**Issue by fly2006zhao** [gecche/laravel-multidomain#5]
if you consider to support the laravel horizon

**Comment by gecche** [comment]
hi,

i never thought about it

i will check asap

thanks

giacomo

**Comment by gecche** [comment]
Hi,

I've just quickly seen in the docs how Horizon works. 

I believe that if you use the --domain option in the cli horizon commands and in the horizon.php config file you use env() values specific for each domain you should be fine.

But maybe I'm wrong: what does not work properly with horizon? 

Cheers

Giacomo

**Comment by fly2006zhao** [comment]
ok , let me try it
Cheers

**Comment by philmarc** [comment]
I am also having troubles with Laravel Horizon.

I have 3 domains, and I started 3 supervisord jobs. Each job has a specific command to run:

```
php artisan horizon --domain=site1.com
php artisan horizon --domain=site2.com
php artisan horizon --domain=site3.com
```
Those 3 processes are running fine.

Now when accessing `site1.com/horizon`, `site2.com/horizon`, `site3.com/horizon`, all of the 3 dashboards have status "Active", but under "Supervisor", where I should see "supervisor-1" running, there is nothing.

When I trigger a job in my site1 app, it is placed on the correct queue, because I can see it in "Recent jobs" of site1.com/horizon. Same for site2 and site3. But those jobs are on "pause" and are not being processed.

It seems like all the setting is correct, but somehow the queued jobs are not processed.

My `.env.site1.com` file has the following (same for `.env.site2.com` and `.env.site3.com`):

```
HORIZON_PREFIX=site1:
REDIS_CONNECTION=site1
```
---

My `config/horizon.php`:

```
    'use' => env('REDIS_CONNECTION'),
```
---

My `config/queue.php`:

```
'redis' => [
    'driver'      => 'redis',
    'connection'    => env('REDIS_CONNECTION', 'default'),
    'queue'       => 'default',
    'retry_after' => 1800,
    'block_for'   => null,
],
```
---

My `config/queue.php`:

```
'redis' => [
    'driver'      => 'redis',
    'connection'    => env('REDIS_CONNECTION', 'default'),
    'queue'       => 'default',
    'retry_after' => 1800,
    'block_for'   => null,
],
```
---

My `config/database.php`:

```
    'redis' => [

        'client' => env('REDIS_CLIENT', 'predis'),

        'default' => [
            'scheme'   => env('REDIS_SCHEME', 'tcp'),
            'path'     => env('REDIS_PATH'),
            'host'     => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port'     => env('REDIS_PORT', 6379),
            'database' => 0,
            'read_write_timeout' => 60,
        ],

        'site1' => [
            'scheme'   => env('REDIS_SCHEME', 'tcp'),
            'path'     => env('REDIS_PATH'),
            'host'     => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port'     => env('REDIS_PORT', 6379),
            'database' => 1,
            'read_write_timeout' => 60,
        ],

        'site2' => [
            'scheme'   => env('REDIS_SCHEME', 'tcp'),
            'path'     => env('REDIS_PATH'),
            'host'     => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port'     => env('REDIS_PORT', 6379),
            'database' => 2,
            'read_write_timeout' => 60,
        ],

        'site3' => [
            'scheme'   => env('REDIS_SCHEME', 'tcp'),
            'path'     => env('REDIS_PATH'),
            'host'     => env('REDIS_HOST', 'localhost'),
            'password' => env('REDIS_PASSWORD', null),
            'port'     => env('REDIS_PORT', 6379),
            'database' => 3,
            'read_write_timeout' => 60,
        ],
    ],
```


Am I missing something?

**Comment by philmarc** [comment]
**Update**: I ran from the console:

```
php artisan optimize:clear --domain=site1.com
php artisan optimize:clear --domain=site2.com
php artisan optimize:clear --domain=site3.com
```

And it seems to be working now
