### ISSUE TITLE
 Class 'Gecche\Multidomain\Foundation\DomainConsoleServiceProvider' not foun     d  

### ISSUE THREAD

**Issue by wa05** [gecche/laravel-multidomain#6]
Hi have this problem in Laravel 5.7

 **Class 'Gecche\Multidomain\Foundation\DomainConsoleServiceProvider' not foun  
  d**  

I did the composer dump-autoload after the update but the error continues...

**Comment by gecche** [comment]
hi,

it seems a bit strange... i need some more info about your project in order to try to help you:

- when such error appear?
- the composer update finished successfully and all the packages files are under the vendor folder? 
- which version of the package have you put in composer.json?
- have you a github repo which I can try?

let me know, thanks

giacomo

Inviato da iPhone

**Comment by wa05** [comment]
Solved doing composer dump-autoload -o 

Also Ive added the class to the providers .. maybe It was an error of my environment

Excuse me and thanks !

**Comment by gecche** [comment]
perfect!

let me know if you have problems and if you like the package please leave a star ;)

thanks

giacomo

Inviato da iPhone
