### ISSUE TITLE
how can test multi domain in localhost ?

### ISSUE THREAD

**Issue by boobProgrammer** [gecche/laravel-multidomain#70]
hi
how can test multi domain in localhost ?
i add  127.0.0.1  myTestDomain.com   in hosts file in windows  but when i run this domain just wamp show on browser

**Comment by gecche** [comment]
Hi,

regardless if whether you use windows, mac or linux, I think you simply should configure your local web server (apache or nginx) in order to serve mytestdomain.com other than localhost.

I close the issue as this seems outside of the scope of the package: if you have a specific issue regarding the package please reopen it

cheers

giacomo
