### ISSUE TITLE
Using cron / scheduler properly

### ISSUE THREAD

**Issue by philmarc** [gecche/laravel-multidomain#8]
If I have 3 domains using the same app, I wonder if I should create three different cron jobs like that:

```
php artisan schedule:run --domain=site1.com
php artisan schedule:run --domain=site2.com
php artisan schedule:run --domain=site3.com
```

Or if I should create just one cron job like that:

```
php artisan schedule:run
```

Since the `App\Console\Kernel.php` is using `use Gecche\Multidomain\Foundation\Console\Kernel as ConsoleKernel;`

The reason I'm asking is because I want to run `$schedule->command('horizon:snapshot')->everyFiveMinutes();` on the 3 domains (each domain has a `php artisan horizon  --domain=siteX.com` set up.)

**Comment by philmarc** [comment]
I realize `php artisan horizon:snapshot` will not work on its own.

You have to specify `php artisan horizon:snapshot --domain=site1.com`

**Comment by gecche** [comment]
Hi,
in order:

1. you need to start a scheduler for each domain with the option `--domain=site1.com` ecc... (this is true for any other external service like supervisor and so on) and 

2. inside the scheduler body you have to set the `--domain` option to each command you want to schedule, so the command inherits the domain. For example

`
   $currentDomain = app()->domain();
   $schedule->command('horizon:snapshot --domain='.$currentDomain)->everyFiveMinutes();
`

As I pointed out in the docs from within the container you cannot change the loaded environment file (this is due to the architecture of the whole framework) so you have to run each scheduler script separately for each domain. 

As far as I know, horizon works fine with multidomain installed, but really I didn't try it deeply.

I hope to have helped you

Giacomo
