### ISSUE TITLE
Jetstream: "Please provide a valid cache path" error

### ISSUE THREAD

**Issue by nomentsoa-andrianjatovo** [gecche/laravel-multidomain#83]
Question: does this work with Jetstream on Laravel 9, because I can't get past through the error "Please provide a valid cache path" on a second domain?

**Comment by gecche** [comment]
Hi,

I'm sorry for the delay but I'm off in August until next week... 
Anyway... I don'y use Jetstream but I'm not sure the problem is related to its use...
It seems that for some reason you didn't create the folder structure in the storage folder for the second domain, but I need some detail more than the error message

Cheers

Giacomo
