### ISSUE TITLE
Caching routes error

### ISSUE THREAD

**Issue by philmarc** [gecche/laravel-multidomain#9]
Running the following commands:

```
php artisan route:cache --domain=site1.com
php artisan route:cache --domain=site2.com
php artisan route:cache --domain=site3.com
```

will cause all 3 domains to use the site3.com routes.

Can you replicate that issue?

**Comment by gecche** [comment]
Ok, honestly, I don’t know why, but I did the job only for config:cache and not for route:cache and others. The issue is the route:cache command write the results into the same file for every domain.

I will update the package in order to do the trick automatically, but however if you are using Laravel 5.7+ is not a real issue because starting from that Laravel version you can choose the cache file for each domain setting the value of `APP_ROUTES_CACHE` in the env files.

You can see those entries in the Laravel `Illuminate\Foundation\Application.php`.

Hope this helps for now

Giacomo

**Comment by gecche** [comment]
Hi, I've just updated the package to address the cache issue.
It should work now without the need to set the cache files in the envs.

Cheers

Giacomo
